# Site settings
title: kyla's blog | Biology blog
description: "A simple blog about things I find interesting, Biology in particular."
url: "http://www.kylaoverbay.github.io"
author:
  name: "Kyla Overbay"
  email: "kylaoverbay@gmail.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
